name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@9425143c4f36d7296c2ce3318a56fb91e2d576f9
    permissions:
      contents: write
    with:
      modules: >-
        ["Lyptus"]

      zip_command: >
        zip -j Lyptus-${{ env.VERSION_TAG }}.zip
        artifacts/*/*.dll
        res/Lyptus.json
